apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-noteapp.fullname" . }}
  labels:
    {{- include "cloud-noteapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: tcp-80-8000
  selector:
    {{- include "cloud-noteapp.selectorLabels" . | nindent 4 }}
  clusterIP: 172.21.80.174
  sessionAffinity: None
  externalTrafficPolicy: Cluster

